apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-studojo-ingress
  namespace: studojo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  tls:
    - hosts:
        - email.studojo.com
      secretName: email-studojo-tls
  rules:
    - host: email.studojo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emailer-service
                port:
                  number: 8087
